### PR TITLE
Add support for plain/text response type

### LINKED ISSUE #376: Cannot use plain/text as response type
**Describe the bug**
When using plain/text as a response type there is an error: TypeError: Cannot use 'in' operator to search for '$ref' in undefined

**To Reproduce**

Method `getResponseSchemaAndNames` for the following specification doesn't work properly.

```yaml
openapi: 3.0.3
info:
  version: v1
  title: Plain text example
paths:
  "/test":
    get:
      summary: Get string value
      responses:
        "200":
          description: Returns value as a string
          content:
            text/plain:
              example: example
```

**Expected behavior**
It should return string as a response type.

### PR DESCRIPTION
**Pull request by JKostov**
Fixes #376

### CODE REVIEW

**Comment by Alan-Cha** [comment]
I need to take a closer look later but I believe [this](https://github.com/IBM/openapi-to-graphql/blob/784b89a64fae38ac8eb37ced6e66143056ae2afe/packages/openapi-to-graphql/src/oas_3_tools.ts#L781) is supposed to handle the case of non-application/json.

**Comment by JKostov** [comment]
The problem is when there is no `schema` in the response type (like the example below) than the `responseSchema` is undefined on [this line](https://github.com/IBM/openapi-to-graphql/blob/784b89a64fae38ac8eb37ced6e66143056ae2afe/packages/openapi-to-graphql/src/oas_3_tools.ts#L766) and than we get the error from issue #376.

```yaml
paths:
  "/test":
    get:
      summary: Get string value
      responses:
        "200":
          description: Returns value as a string
          content:
            text/plain:
              example: example
```

**Comment by Alan-Cha** [comment]
I see! In that case, could we just reorganize the code so that we still use [this](https://github.com/IBM/openapi-to-graphql/blob/784b89a64fae38ac8eb37ced6e66143056ae2afe/packages/openapi-to-graphql/src/oas_3_tools.ts#L781) but it checks if a `responseSchema` exists first?

**Comment by JKostov** [comment]
Yes, it should fix the issue.

**Comment by Alan-Cha** [comment]
@JKostov I've addressed this with #391. Thank you for all your help!

**Pull request closed without merging**
